/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2016-05-12 06:25:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 Connection conn=null;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect1.jsp", Long.valueOf(1448811316161L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
	
	try{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sourabh");
		System.out.println("driver  found");
	}
	catch(Exception e) {
System.out.println("driver not found");
}
	
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html><!-- InstanceBegin template=\"/Templates/article_about_us.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>About Us - STUDENT BANK, KOLKATA</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<A href=\"index.html\"><IMG SRC=\"images/home1.gif\"></IMG></A>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              </TABLE>\r\n");
      out.write("          \r\n");
      out.write("                           \r\n");
      out.write("                  <table width=\"100%\"  border=\"0\" cellspacing=\"10\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"bodyheading\"><!-- InstanceBeginEditable name=\"Heading\" --><font color = \"white\">About Us</font><!-- InstanceEndEditable --></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"bodytext\"><!-- InstanceBeginEditable name=\"Body of Article\" -->\r\n");
      out.write("                              <p align=\"center\" class=\"bodytextheading\"><img id=\"no-border\" src=\"images/bank2.jpg\" width=\"500\" height=\"268\"><br>\r\n");
      out.write("                              <font color = \"white\">\r\n");
      out.write("                                <span class=\"style2\">STUDENT BANK</span></p>\r\n");
      out.write("                        <p align=\"justify\" class=\"bodytextheading\">                  </p>\r\n");
      out.write("                        <br><br>\r\n");
      out.write("                        <p align=\"justify\">                                STUDENT BANK  is one of the  BANKs in KOLKATA. Founded as a Online BANK in 2015 in Kolkata, it is a private institution run by the Techno India Society.</p>\r\n");
      out.write("                              <p align=\"justify\"> STUDENT BANK is affiliated to the Central Board of Bank (CBB), which is the largest educational board in the country. It is recognized by the Department of Information Technology, Techno India, Kolkata. Over 5000 BANKs in India, with over 80,000 students, are members of the Board. </p>\r\n");
      out.write("                              <p align=\"justify\">                                The BANK is also affiliated to the Indian Public BANKs' Conference (IPSC), and the National Progressive BANKs' Conference (NPSC). The members of these organisations include some of the premier BANKs in the country.</p>\r\n");
      out.write("                              <p align=\"justify\"> Life at student bank centres on a shared commitment to academic excellence, intellectual growth, art, athletics, high standards of ethical awareness, sportsmanship, and community service. The BANK's traditions and accessibility to a broad curriculum add depth to each student&rsquo;s life.<br>\r\n");
      out.write("                                The BANK upholds the founders' commitment to excellence in all fields, with emphasis on its motto Service Before Self.<br>\r\n");
      out.write("                                </p>\r\n");
      out.write("                              <p align=\"justify\" class=\"bodytextheading\">BANK Profile</p>\r\n");
      out.write("                              <p align=\"justify\"> STUDENT BANK is a co-educational day-cum-boarding BANK, with approximately 9,500 coustemer on its rolls. These children, in the Junior and Senior branches, study in the three different campuses at East of Kailash, Vasant Vihar and c.p.</p>\r\n");
      out.write("                              <p align=\"justify\"> The BANK is among the most distinguished members of the Ravi Public BANK, c.p.. It is a path breaker in the pursuit of excellence. Its endeavour of integrating quality with quantity is reflected in the pivotal role it has played in the setting up of DPS Vasant Kunj, DPS Faridabad and DPS Manali at the national level. It has also promoted three BANKs abroad in Kuwait, Nepal and Indonesia. As their Linking BANK it also co-ordinates their activities. </p>\r\n");
      out.write("                              <p align=\"justify\"> The BANK has also extended itss expertise further and in collaboration with the Government of Haryana, has taken up 3 BANKs in the under-privileged area of Mewat, to augment and enhance their standards and make them more conducive to teaming.</p>\r\n");
      out.write("                              <p align=\"justify\"> The BANK considers education to be a life-long process which should have a strong foundation. The goal of the BANK is to inculcate in the coustemer a love for learning and a desire to excel at every level. The BANK also aims at equipping the coustemer with the intellectual and practical skills that are necessary to meet the challenges in the future.</p>\r\n");
      out.write("                              <p align=\"justify\"> To sum up, the mission of  TECHNO INDIA BANK &quot;to open doors and open minds&quot; and prepare the ground for the future of the nation.</p>\r\n");
      out.write("                              <p align=\"justify\" class=\"bodytextheading\"> Our Culture</p>\r\n");
      out.write("                              <p align=\"justify\"> In the portals of  STUDENT BANK, c.p., c.p. coustemer discover their own talents, and get an opportunity to develop them to the fullest. The BANK provides an invigorating and competitive atmosphere, created by excellent facilities and guidance provided by a highly qualified and dedicated faculty.</p>\r\n");
      out.write("                              <p align=\"justify\"> The values, which are ingrained help to promote confidence, direction, and critical thinking skills, leading to the development of well-adjusted, adaptable and integrated personalities. In other words,  STUDENT BANK, c.p. offers comprehensive and holistic education.</p>\r\n");
      out.write("                              <p align=\"justify\"> Besides being committed to academic excellence and providing education for all round development, another special characteristic of DPS R.K. Puram is the appreciation of the worth of the each student. The BANK is equally committed to the under-represented and less-privileged segments of the population, such as gifted applicants whose parents could not attend BANK, and children with high potential facing difficult financial circumstances.</p>\r\n");
      out.write("                              <p align=\"justify\"> A major landmark development has been the inclusion of the physically and mentally handicapped children into the mainstream of BANK life. This  contributes to a strong sense of community life, so characteristic of the BANK. In other words, children belonging to every strata of society are given the opportunity to study here. The BANK, does not in any way, discriminate on the basis of race, colour, religion, sex, caste or creed, in the implementation of its admission policy.</p>\r\n");
      out.write("                              <p align=\"justify\"> These qualities have placed  STUDENT BANK, c.p. on the forefront. There has been a continuity of purpose, underlying the change and growth of the BANK. Over the years,  STUDENT BANK has steadily reflected a spirit of innovation in response to need, and has broadened its educational mission, by creating an academic environment that fosters close association and the exchange of ideas with some of the top BANKs in the nation and the world.</p>\r\n");
      out.write("                              <p align=\"justify\"> Its membership with the IPSC  has brought it into regular interaction with BANKs of national standing such as Mayo College, Ajmer; Scindia BANK, Gwalior; The Doon BANK, Dehradun; Bishop Cotton, Simla Hills; St. Xavier's and La-Martiniere at Calcutta; which has further inculcated a healthy spirit of competition and strong bonds of brotherhood, conducive to national integration.</p>\r\n");
      out.write("                              <p align=\"justify\"> All the academic programs and activities at  STUDENT BANK work towards one purpose - to help coustemer develop lives of significance for themselves and for others, true to the traditions of the BANK Motto &quot;Service Before Self&quot;.</p>\r\n");
      out.write("                      <!-- InstanceEndEditable --></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </font>\r\n");
      out.write("                           \r\n");
      out.write("                </td><td width=\"25\">&nbsp;</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("            <table width=\"100%\" height=\"26\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("               </table>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("  <table width=\"100%\"  border=\"0\" cellspacing=\"7\" cellpadding=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><div align=\"center\"><span class=\"bottombar\"><strong><font color=\"white\">&copy; STUDENT  BANK , KOLKATA , All Rights Reserved.</font> </strong></span></div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr> \r\n");
      out.write("          <td>\r\n");
      out.write("<div align=\"center\"> </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("  <table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><img src=\"\" width=\"915\" height=\"1\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
