/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2016-05-17 08:51:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class myupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 Connection conn=null;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect1.jsp", Long.valueOf(1448811316161L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
	
	try{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","sourabh");
		System.out.println("driver  found");
	}
	catch(Exception e) {
System.out.println("driver not found");
}
	
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
String username="",password="",repassword="",address="";
int accountno ,amount,phone;
Statement pst=null;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>VIEW ACCOUNT DETAILS</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top_links\">\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<h1>STUDENT BANK<span class=\"style1\"></span></h1>\r\n");
      out.write("    <h2>Online Service</h2>\r\n");
      out.write("    <A href=\"index.html\"><IMG SRC=\"images/home1.gif\"></IMG></A>\t\r\n");
      out.write("</div>\r\n");
      out.write("<font size =6 color =\"white\">\r\n");
      out.write("<table border=\"2\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>ACCOUNT NO</td>\r\n");
      out.write("<td>USER NAME</td>\r\n");
      out.write("<td>PASSWORD</td>\r\n");
      out.write("<td>AMOUNT</td>\r\n");
      out.write("<td>ADDRESS</td>\r\n");
      out.write("<td>PHONE</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</font>\r\n");
      out.write("\r\n");
 
try{
pst=conn.createStatement();
String a=request.getParameter("n1");
out.println("<u>INFORMATION OF  ACCOUNT NO  <b>"+a+"</b></u>");
out.println("<br><br>");
ResultSet rs=pst.executeQuery("Select * from account where accountno="+a);
while(rs.next())
{
accountno=rs.getInt(1);
username=rs.getString(2);
password=rs.getString(3);
amount=rs.getInt(5);
address=rs.getString(6);
phone=rs.getInt(7);

      out.write("\r\n");
      out.write("<tr><td>");
      out.print(accountno);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(username);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(password);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(amount);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(address);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(phone);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
}
      out.write("\r\n");
      out.write("</table>\r\n");

rs.close();
conn.close();
}catch(Exception e){}

      out.write("\r\n");
      out.write("   \r\n");
      out.write(" </p>\r\n");
      out.write(" <br>\r\n");
      out.write(" <a href = \"view1.jsp\"><font color = white size = 5>BACK</a></font>\r\n");
      out.write(" <br><br>\r\n");
      out.write(" <a href = \"adminlogin.html\"><font color = white size = 5>LOGOUT</a></font>\r\n");
      out.write(" \r\n");
      out.write("</form>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
